#ifndef SHARED_H__
#define SHARED_H__

#include "shared_EXPORTS.h"  // automatically generated by cmake 
                             // by the GENERATE_EXPORT_HEADER macro

extern "C" void SHARED_EXPORT f();

class SHARED_EXPORT X {
public:
  X();
  void mX();
};

#endif
